services:
  db:
    # hostname: pg15
    image: postgres:15
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo16@2024
      - POSTGRES_DB=postgres
    # restart: always             # run as a service
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - odoo-network

  odoo16:
    hostname: oo16-ee
    image: 36aa63f72273
    user: root
    depends_on:
      - db
    ports:
      - "10016:8069"
      - "20016:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=db
      - PORT=5432
      - USER=odoo
      - PASSWORD=odoo16@2024
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      #- ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
       - ./addons:/opt/odoo/custom-addons
       - ./etc:/opt/odoo/etc
    networks:
      - odoo-network
    # restart: always             # run as a service
networks:
  odoo-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450