version: '3.7'

services:

  mssql2019:
    hostname: mssql2019
    restart: always
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - MSSQL_SA_PASSWORD=KeeruL1nepar00l
      - ACCEPT_EULA=Y
      - MSSQL_PID=Standard
      - MSSQL_AGENT_ENABLED=true
      - MSSQL_TCP_PORT=8888
      - MSSQL_COLLATION=Estonian_CI_AS
    ports:
      - '8888:8888'
    volumes:
      - sqldata:/var/opt/mssql
      - sqlbackup:/var/opt/mssql/koopia
    deploy:
      replicas: 1

  dotnet:
    hostname: dotnet
    restart: always
    image: mcr.microsoft.com/dotnet/aspnet:5.0
    environment:
# asp.net core app-i saab seadistada sajal erineval viisil. konteineris deploymentil on mõistlikum kasutada keskkonnamuutujaid, siis ei pea
# tegelema appsettings failidega ja saab jooksvalt asju muuta
#
# vaikimisi käivitub asp.net core pordis 5001
      - ASPNETCORE_URLS=http://+:8880
# keskkonna nimi peaks alati määratud olema asp.net core puhul, sest see võimaldab äpis rakendada .net core platvormi tuge
# erinevate käitumisreziimideks
      - ASPNETCORE_ENVIRONMENT=Development
# defineerime baasi ühenduse samuti keskkonnamuutujas, sest siis saab see olla kooskõlas samas compse failis nimetatud
# sql serveri konfiga - vt. Server - viitab siinsamas määratud serverile
      - ASPNETCORE_ConnectionStrings__TerminalContext=Server=tcp:mssql2019,8888;Initial Catalog=artium_pda_test;Persist Security Info=False;User ID=pda_ws_test;Password=skh2K3j.2jasHhr43kf-fJrH;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;
# ei oma hetkel tähtsust, kuna entrypointis on antud täistee
      - WORKDIR=/
# vt. https://github.com/compose-spec/compose-spec/blob/master/spec.md command ja entrypoint kirjeldust
# command ei ole eraldi vajalik, sest compose spetsi järgi, kui entrypoint on määratud, siis see kirjutab
# üle ka commandi. St. entrypointi esimene element ongi command
# Googles antud viited ENV abil entrypointi määramisel ei tööta eelnevalt kompileeritud asp.net core
# rakenduse puhul, sest tegemist ei ole Dockeri imagega.
    entrypoint:
      - dotnet
      - app/VTMF.Terminal.WS.dll
    ports:
      - '8880:8880'
    volumes:
      - dotnetapp:/app
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy-ext
        - traefik.constraint-label=traefik-public
        - traefik.http.middlewares.dotnet-https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.dotnet-https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.dotnet-public-http.rule=Host(`artiumdotnet.pilveserv.eu`)
        - traefik.http.routers.dotnet-public-http.entrypoints=http
        - traefik.http.routers.dotnet-public-http.middlewares=dotnet-https-redirect
        - traefik.http.routers.dotnet-public-https.rule=Host(`artiumdotnet.pilveserv.eu`)
        - traefik.http.routers.dotnet-public-https.entrypoints=https
        - traefik.http.routers.dotnet-public-https.tls=true
        - traefik.http.routers.dotnet-public-https.service=dotnet
        - traefik.http.routers.dotnet-public-https.tls.certresolver=le
        - traefik.http.services.dotnet.loadbalancer.server.port=8880
  networks:
      - proxy-ext


volumes:
  sqldata:
  sqlbackup:
  dotnetapp:

networks:
  proxy-ext:
    external: true
