version: '3.3'

services:

  mssql2019-2:
    hostname: mssql2019-2
    restart: always
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - MSSQL_SA_PASSWORD=KeeruL1nepar00l
      - ACCEPT_EULA=Y
      - MSSQL_PID=Standard
      - MSSQL_AGENT_ENABLED=true
      - MSSQL_TCP_PORT=8888
      - MSSQL_COLLATION=Estonian_CI_AS
    ports:
      - '8887:8888'
    volumes:
      - sqldata:/var/opt/mssql
      - sqlbackup:/var/opt/mssql/koopia
    deploy:
      replicas: 1

  dotnet-2:
    hostname: dotnet-2
    restart: always
    image: mcr.microsoft.com/dotnet/aspnet:5.0
    environment:
#asp.net core app can be configured in a hundred different ways. container deployment is more reasonable to use environment variables,
# you do not have to
# handle appsettings files and can change things on an ongoing basis
#
# defaults to asp.net core port 5001
      - ASPNETCORE_URLS=http://+:8879
# keskkonna nimi peaks alati määratud olema asp.net core puhul, sest see võimaldab äpis rakendada .net core platvormi tuge
# erinevate käitumisreziimideks
      - ASPNETCORE_ENVIRONMENT=Development
# The environment name should always be specified for asp.net core, as this allows the app to implement .net core platform support
# for different behavioral modes
      - ASPNETCORE_ConnectionStrings__TerminalContext=Server=tcp:mssql2019-2,8888;Initial Catalog=artium_pda_test;Persist Security Info=False;User ID=pda_ws_test;Password=skh2K3j.2jasHhr43kf-fJrH;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;
# does not matter at this time because the entrypoint is a full path
      - WORKDIR=/
# see https://github.com/compose-spec/compose-spec/blob/master/spec.md command and entrypoint description
# the command is not needed separately, because according to the compose specification, if an entrypoint is specified, it writes
# also over the command. St. the first element of the entrypoint is command
# References provided by Google When specifying an entrypoint using ENV, the pre-compiled asp.net core does not work
# for the application because it is not a Docker image.
    entrypoint:
      - dotnet
      - app/VTMF.Terminal.WS.dll
    ports:
      - '8879:8880'
    volumes:
      - dotnetapp:/app
    deploy:
      replicas: 1



volumes:
  sqldata:
  sqlbackup:

  dotnetapp:
  dotnetapp2:
