web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'ggit.viiul.ee'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://ggit.viiul.ee'
      gitlab_rails['gitlab_email_from'] = 'git@viiul.com'
      gitlab_rails['gitlab_email_display_name'] = 'GGit'
      gitlab_rails['gitlab_email_reply_to'] = 'git@viiul.com'
      gitlab_rails['gitlab_shell_ssh_port'] = 2211
      gitlab_rails['smtp_enable'] = true
      gitlab_rails['smtp_address'] = "smtp.zone.ee"
      gitlab_rails['smtp_port'] = 465
      gitlab_rails['smtp_user_name'] = "git@viiul.com"
      gitlab_rails['smtp_password'] = "Ep6xRCAeGoerSWE23"
      gitlab_rails['smtp_domain'] = "viiul.com"
      gitlab_rails['smtp_authentication'] = "login"
      gitlab_rails['smtp_enable_starttls_auto'] = true
      gitlab_rails['smtp_tls'] = true

  ports:
    - '80:80'
    - '443:443'
    - '2211:22'
  volumes:
    - '/srv/gitlab/config:/etc/gitlab'
    - '/srv/gitlab/logs:/var/log/gitlab'
    - '/srv/gitlab/data:/var/opt/gitlab'
