version: "3.6"
services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    ports:
      - "2214:22"
      - "8085:80"
      - "44312:443"
    volumes:
      - ggit_data:/var/opt/gitlab
      - ggit_logs:/var/log/gitlab
      - ggit_config:/etc/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    configs:
      - source: gitlab
        target: /omnibus_config.rb
    secrets:
      - gitlab_root_password
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    deploy:
      mode: replicated
      replicas: 4
configs:
  gitlab:
    file: ./gitlab.rb
secrets:
  gitlab_root_password:
    file: ./root_password.txt
volumes:
  ggit_data:
  ggit_logs:
  ggit_config:
networks:
  traefik-public:
    external: true
