version: '3.3'

services:

  postgre:
    hostname: postgre
    image: crunchydata/crunchy-postgres:centos7-10.9-2.4.1
    restart: always
    environment:
      - PGHOST=/tmp
      - MAX_CONNECTIONS=250
      - MAX_WAL_SENDERS=5
      - PG_MODE=primary
      - PG_PRIMARY_USER=primaryuser
      - PG_PRIMARY_PASSWORD=password
      - PG_DATABASE=testdb
      - PG_USER=testuser
      - PG_PASSWORD=password
      - PG_ROOT_PASSWORD=password
      - PG_PRIMARY_PORT=5432
    volumes:
      - dbhost-vol:/pgdata
      - dbhost-backrestrepo:/backrestrepo
      - dbhost-pgwal:/pgwal
      - dbhost-backup:/backup
      - dbhost-recover:/recover
      - dbhost-pgconf:/pgconf
      - dbhost-sshd:/sshd
    ports:
      - 5432
    networks:
      - net

  pgadmin:
    hostname: pgadmin
    image: thajeztah/pgadmin4:latest
    networks:
      - net
    ports:
      - 9090:5050
    volumes:
      - pgadmin-data:/pgadmin/

  redis:
    image: redis:6
    hostname: redis
    restart: always
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis:/data
      - redisetc:/etc
    networks:
      - net

  owncloud4:
    hostname: owncloud4
    image: owncloud/server:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - net
      - proxy-ext
    volumes:
      - oc4oc:/var/www/owncloud/
      - oc4disk:/mnt/data/
    environment:
      - OWNCLOUD_DOMAIN=z7z.pilveserv.eu
      - OWNCLOUD_DB_TYPE=pgsql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=postgres
      - OWNCLOUD_DB_PASSWORD=password
      - OWNCLOUD_DB_HOST=postgre
      - OWNCLOUD_ADMIN_USERNAME=guru
      - OWNCLOUD_ADMIN_PASSWORD=111
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy-ext
      - traefik.http.routers.owncloud4-secure.entrypoints=websecure
      - traefik.http.routers.owncloud4-secure.rule=Host(`z7z.pilveserv.eu`)
      - traefik.http.routers.owncloud4-secure.service=owncloud4
      - traefik.http.services.owncloud4.loadbalancer.server.port=8080

volumes:
  oc4oc:
  oc4disk:
  dbhost-vol:
  dbhost-backrestrepo:
  dbhost-pgwal:
  dbhost-backup:
  dbhost-recover:
  dbhost-pgconf:
  dbhost-sshd:
  pgadmin-data:
  redis:
  redisetc:

networks:
  net:
    external: true
  proxy-ext:
    external: true
