version: '3.7'

services:
  traefik:
    image: traefik:1.7.13
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    command:
      --api
      --acme
      --acme.storage=/certs/acme.json
      --acme.entryPoint=https
      --acme.httpChallenge.entryPoint=http
      --acme.onHostRule=true
      --acme.onDemand=false
      --acme.acmelogging=true
      --acme.email=${EMAIL:-info@viiul.com}
      --docker
      --docker.swarmMode
      --docker.domain=${DOMAIN:-pilveserv.eu}
      --docker.watch
      --defaultentrypoints=http,https
      --entrypoints='Name:http Address::80'
      --entrypoints='Name:https Address::443 TLS'
      --logLevel=INFO
      --accessLog
      --metrics
      --metrics.prometheus
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_certs:/certs
    configs:
      - source: traefik_htpasswd
        target: /etc/htpasswd
    networks:
      - public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.docker.network=public
        - traefik.port=8080
        - traefik.backend=traefik
        - traefik.enable=true
        - traefik.frontend.rule=Host:nginx.pilveserv.eu
        - traefik.frontend.auth.basic.usersFile=/etc/htpasswd
        - traefik.frontend.headers.SSLRedirect=true
        - traefik.frontend.entryPoints=http,https

  db:
    image: postgres:11
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
    ports:
      - 5432:5432
    networks:
      - net
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: 'postgres_db'
      volumes: dbdata:/var/lib/postgresql/data

  pgadmin:
    hostname: pgadmin
    image: thajeztah/pgadmin4:latest
    ports:
      - 5050:5050
    networks:
      - net
    volumes:
      - pgadmindata:/pgadmin/

  ledger:
    hostname: ledger
    image: drnoa/sqlledger-docker:latest
    ports:
      - 8099:80
    networks:
      - net
    volumes:
      - ledgerdata:/var/lib/postgresql
      - ledgerfiles:/var/www/html

volumes:
  pgadmindata:
  dbdata:
  ledgerdata:
  nginx-config:
  nginx-web:
  traefik_certs:
  ledgerfiles:

networks:
  net:
    driver: overlay
    attachable: true

  public:
    driver: overlay
    name: public

configs:
  traefik_htpasswd:
    file: ./htpasswd
