version: "3.4"

services:
  ################################################
  ####        Traefik Proxy Setup           #####
  ###############################################
  proxy:
    image: traefik
    #restart: always
    #container_name: traefik
    ports:
      - "80:80" # <== http
      - "8080:8080" # <== :8080 is where the dashboard runs on
      - "443:443" # <== https
    command:
      #### These are the CLI commands that will configure Traefik and tell it how to work! ####
      ## API Settings - https://docs.traefik.io/operations/api/, endpoints - https://docs.traefik.io/operations/api/#endpoints ##
      - --api.insecure=true # <== Enabling insecure api, NOT RECOMMENDED FOR PRODUCTION
      - --api.dashboard=true # <== Enabling the dashboard to view services, middlewares, routers, etc...
      - --api.debug=true # <== Enabling additional endpoints for debugging and profiling
      ## Log Settings (options: ERROR, DEBUG, PANIC, FATAL, WARN, INFO) - https://docs.traefik.io/observability/logs/ ##
      - --log.level=DEBUG # <== Setting the level of the logs from traefik
      ## Provider Settings - https://docs.traefik.io/providers/docker/#provider-configuration ##
      - --providers.docker # <== Enabling docker as the provider for traefik
      - --providers.docker.exposedbydefault=false # <== Don't expose every container to traefik, only expose enabled ones
      - --providers.file.filename=/dynamic.yaml # <== Referring to a dynamic configuration file
      - --providers.docker.network=viiulnet # <== Operate on the docker network named viiul-net
      - --providers.docker.swarmMode=true # activate swarmMode
      ## Entrypoints Settings - https://docs.traefik.io/routing/entrypoints/#configuration ##
      - --entrypoints.vtraefik.address=:80 # <== Defining an entrypoint for port :80 named vtraefik
      - --entrypoints.vtraefik-secured.address=:443 # <== Defining an entrypoint for https on port :443 named vtraefik-secured
      ## Certificate Settings (Let's Encrypt) -  https://docs.traefik.io/https/acme/#configuration-examples ##
      - --certificatesresolvers.viiulresolver.acme.tlschallenge=true # <== Enable TLS-ALPN-01 to generate and renew ACME certs
      - --certificatesresolvers.viiulresolver.acme.email=janno@gurud.ee # <== Setting email for certs
      - --certificatesresolvers.viiulresolver.acme.storage=/letsencrypt/acme.json # <== Defining acme file to store cert information
      - --certificatesresolvers.viiulresolver.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory # Stage server for acme httpChallenge
      - --certificatesresolvers.viiulresolver.acme.httpchallenge.entrypoint=vtraefik
    volumes:
      - ./letsencrypt:/letsencrypt # <== Volume for certs (TLS)
      - /var/run/docker.sock:/var/run/docker.sock # <== Volume for docker admin
      - ./dynamic.yaml:/dynamic.yaml # <== Volume for dynamic conf file, **ref: line 27
    networks:
      - viiulnet # <== Placing traefik on the network named web, to access containers on this network
    labels:
      #### Labels define the behavior and rules of the traefik proxy for this container ####
      - "traefik.enable=true" # <== Enable traefik on itself to view dashboard and assign subdomain to view it
      - "traefik.http.routers.api.rule=Host(`conductormanager.viiul.com`)" # <== Setting the domain for the dashboard
      - "traefik.http.routers.api.service=api@internal" # <== Enabling the api to be a service to access
      - "traefik.http.routers.api.entrypoints=vtraefik"
      - "traefik.http.routers.api.middlewares=redirect@file" # <== This is a middleware to redirect to https
      - "traefik.http.routers.api-secured.rule=Host(`conductormanager.viiul.com`)" # <== Your Domain Name for the https rule
      - "traefik.http.routers.api-secured.entrypoints=vtraefik-secured" # <== Defining entrypoint for https, **ref: line 31
      - "traefik.http.routers.api-secured.tls.certresolver=viiulresolver" # <== Defining certsresolvers for https


#   ################################################
#   ####         Site Setup Container         #####
#   ##############################################
#   wordpress: # <== we aren't going to open :80 here because traefik is going to serve this on entrypoint 'web'
#     ## :80 is already exposed from within the container ##
#     image: wordpress
#     #restart: always
#     #container_name: wp
#     environment:
#       WORDPRESS_DB_HOST: db
#       WORDPRESS_DB_USER: exampleuser
#       WORDPRESS_DB_PASSWORD: examplepass
#       WORDPRESS_DB_NAME: exampledb
#     volumes:
#       - wordpress:/var/www/html
#     networks:
#       - viiulnet
#       - wordpressbackend
#     labels:
#       #### Labels define the behavior and rules of the traefik proxy for this container ####
#       - "traefik.enable=true" # <== Enable traefik to proxy this container
#       - "traefik.http.routers.wordpress.rule=Host(`wordpress.viiul.com`)" # <== Your Domain Name goes here for the http rule
#       - "traefik.http.routers.wordpress.entrypoints=vtraefik" # <== Defining the entrypoint for http, **ref: line 30
#       - "traefik.http.routers.wordpress.middlewares=redirect@file" # <== This is a middleware to redirect to https
#       - "traefik.http.routers.wordpress-secured.rule=Host(`wordpress.viiul.com`)" # <== Your Domain Name for the https rule
#       - "traefik.http.routers.wordpress-secured.entrypoints=vtraefik-secured" # <== Defining entrypoint for https, **ref: line 31
#       - "traefik.http.routers.wordpress-secured.tls.certresolver=viiulresolver" # <== Defining certsresolvers for https
#
#   ################################################
#   ####     DB Container not on traefik      #####
#   ##############################################
#   db:
#     image: mysql:5.7
#     #restart: always
#     environment:
#       MYSQL_DATABASE: exampledb
#       MYSQL_USER: exampleuser
#       MYSQL_PASSWORD: examplepass
#       MYSQL_RANDOM_ROOT_PASSWORD: '1'
#     volumes:
#       - db:/var/lib/mysql
#     networks:
#       - wordpress-backend
#
networks:
  viiulnet:
    external: false
  wordpressbackend:
    external: false
#
# volumes:
#   wordpress:
#     external: true
#   db:
#     external: true
